wandb_version: 1

beta_pool:
  desc: null
  value: 0.656026188255396
hgcn_mix1:
  desc: null
  value: 2
hgcn_mix2:
  desc: null
  value: 1
lr:
  desc: null
  value: 0.05
pre_lr:
  desc: null
  value: 0.01
regs1:
  desc: null
  value: 0.3
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705914567.871059
    t:
      1:
      - 1
      - 5
      - 49
      - 53
      - 55
      - 76
      - 77
      3:
      - 23
      4: 3.10.12
      5: 0.15.9
      8:
      - 5
